// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.18063
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Specifications
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class SubdivisionFeature : Xunit.IUseFixture<SubdivisionFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Subdivision.feature"
#line hidden
        
        public SubdivisionFeature()
        {
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Subdivision", "In order to avoid silly mistakes\r\nAs a math idiot\r\nI want to be told the sum of t" +
                    "wo numbers", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line 7
 testRunner.Given("We have Parcel with Uid = \"Property 2\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 9
 testRunner.And("Registration transaction \"REGO\" with No.\"TRN-002\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 11
 testRunner.And("Transaction No.\"TRN-002\" has target LAUnit \"Occupancy-LA-02\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 12
 testRunner.And("Transaction No.\"TRN-002\" has property with Uid = \"Property 2\" in LAUnit \"Occupanc" +
                    "y-LA-02\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 13
 testRunner.And("Transaction No.\"TRN-002\" has party \"Tim Taler\" with role \"Grantee\" associated wit" +
                    "h LAUnit \"Occupancy-LA-02\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 14
 testRunner.And("Transaction No.\"TRN-002\" has party \"Sara Taler\" with role \"Grantee\" associated wi" +
                    "th LAUnit \"Occupancy-LA-02\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 17
 testRunner.When("transaction \"TRN-002\" is completed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
        }
        
        public virtual void SetFixture(SubdivisionFeature.FixtureData fixtureData)
        {
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Subdivision")]
        [Xunit.TraitAttribute("Description", "Subdivision produces 2 new properties and no additional interests registered on s" +
            "ource")]
        public virtual void SubdivisionProduces2NewPropertiesAndNoAdditionalInterestsRegisteredOnSource()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Subdivision produces 2 new properties and no additional interests registered on s" +
                    "ource", new string[] {
                        "mytag"});
#line 20
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 21
 testRunner.Given("Registration transaction \"SUBS\" with No.\"TRN-003\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 22
 testRunner.And("Transaction No.\"TRN-003\" has source LAUnit \"Occupancy-LA-02\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 23
 testRunner.And("Transaction No.\"TRN-003\" has target LAUnit \"Occupancy-LA-03\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 24
 testRunner.And("Transaction No.\"TRN-003\" has target LAUnit \"Occupancy-LA-04\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 25
 testRunner.And("Transaction No.\"TRN-003\" has property with Uid = \"Property 2\" in LAUnit \"Occupanc" +
                    "y-LA-02\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 26
 testRunner.And("Transaction No.\"TRN-003\" has property with Uid = \"Property 3\" in LAUnit \"Occupanc" +
                    "y-LA-03\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 27
 testRunner.And("Transaction No.\"TRN-003\" has property with Uid = \"Property 4\" in LAUnit \"Occupanc" +
                    "y-LA-04\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 28
 testRunner.And("Transaction No.\"TRN-003\" has party \"Tim Taler\" with role \"Grantee\" associated wit" +
                    "h LAUnit \"Occupancy-LA-03\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 29
 testRunner.And("Transaction No.\"TRN-003\" has party \"Sara Taler\" with role \"Grantee\" associated wi" +
                    "th LAUnit \"Occupancy-LA-04\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 30
 testRunner.When("transaction \"TRN-003\" is completed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                SubdivisionFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                SubdivisionFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
